controller:
  service:
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.0.10
  config:
    ssl-protocols: "TLSv1.3"
    ssl_prefer_server_ciphers: 'off'
    log-format-escape-json: "true"
    log-format-upstream: >-
      {
      "body_bytes_sent":"$body_bytes_sent",
      "host":"$host",
      "http_referrer":"$http_referer",
      "http_user_agent":"$http_user_agent",
      "proxy_add_x_forwarded_for":"$proxy_add_x_forwarded_for",
      "proxy_alternative_upstream_name":"$proxy_alternative_upstream_name",
      "proxy_upstream_name":"$proxy_upstream_name",
      "remote_addr":"$remote_addr",
      "remote_user":"$remote_user",
      "request":"$request",
      "request_id":"$req_id",
      "request_length":"$request_length",
      "request_method":"$request_method",
      "request_path":"$uri",
      "request_proto":"$server_protocol",
      "request_query":"$args",
      "request_time":"$request_time",
      "status":"$status",
      "time":"$time_local",
      "upstream_addr":"$upstream_addr",
      "upstream_response_length":"$upstream_response_length",
      "upstream_response_time":"$upstream_response_time",
      "upstream_status":"$upstream_status"
      }
